# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Trigger the pipeline on any tag
trigger:
  tags:
    include:
    - '*'
  # Exclude all branches branches
  branches:
    exclude:
    - '*'

# Use a Windows agent pool
pool:
  vmImage: 'windows-latest'

# Define a stage for building the app
stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    # Install Electron Forge
    - script: npm install -g @electron-forge/cli @electron-forge/maker-zip
      displayName: 'Install Electron Forge'
    # Install dependencies
    - script: npm install
      displayName: 'Install dependencies'
    # Build the app using Electron Forge with the tag name as the version
    - script: electron-forge make --platform win32 --version $(Build.SourceBranchName)
      displayName: 'Packaging'
    - task: CopyFiles@2
      displayName: 'Copying to target folder'
      inputs:
       SourceFolder: out/make/zip/win32/
       Contents: '**/*.zip'
       TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # Publish the output files as an artifact
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
        publishLocation: Container